//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.Idioma {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cliente.Idioma.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        internal static string CabecerasDGVArchivoCompartidoActivo {
            get {
                return ResourceManager.GetString("CabecerasDGVArchivoCompartidoActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre-Tamaño-Descripcion.
        /// </summary>
        internal static string CabecerasDGVArchivoCompartidoArreglo {
            get {
                return ResourceManager.GetString("CabecerasDGVArchivoCompartidoArreglo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        internal static string CabecerasDGVArchivoCompartidoEliminar {
            get {
                return ResourceManager.GetString("CabecerasDGVArchivoCompartidoEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario-Descripcion.
        /// </summary>
        internal static string CabecerasDGVSolcitarArreglo {
            get {
                return ResourceManager.GetString("CabecerasDGVSolcitarArreglo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir.
        /// </summary>
        internal static string CabecerasDGVSolicitarCompartir {
            get {
                return ResourceManager.GetString("CabecerasDGVSolicitarCompartir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apagar equipo.
        /// </summary>
        internal static string lblConfiguracionesRapidasApagar {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasApagar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar aplicacion.
        /// </summary>
        internal static string lblConfiguracionesRapidasCerrarApp {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasCerrarApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuerda que deberás configurarlas cada vez que inicies BitNode.
        /// </summary>
        internal static string lblConfiguracionesRapidasDescripcion {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Al finalizar descargas, desea:.
        /// </summary>
        internal static string lblConfiguracionesRapidasDeseo {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasDeseo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hibernar equipo.
        /// </summary>
        internal static string lblConfiguracionesRapidasHibernar {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasHibernar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hacer nada.
        /// </summary>
        internal static string lblConfiguracionesRapidasNoHacerNada {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasNoHacerNada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suspender equipo.
        /// </summary>
        internal static string lblConfiguracionesRapidasSuspender {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasSuspender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones rapidas.
        /// </summary>
        internal static string lblConfiguracionesRapidasTitulo {
            get {
                return ResourceManager.GetString("lblConfiguracionesRapidasTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sobre bitNode.
        /// </summary>
        internal static string lblMenuAbout {
            get {
                return ResourceManager.GetString("lblMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Compartir.
        /// </summary>
        internal static string lblMenuCompartir {
            get {
                return ResourceManager.GetString("lblMenuCompartir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuracion.
        /// </summary>
        internal static string lblMenuConfiguracion {
            get {
                return ResourceManager.GetString("lblMenuConfiguracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configuraciones.
        /// </summary>
        internal static string lblMenuConfiguracionesR {
            get {
                return ResourceManager.GetString("lblMenuConfiguracionesR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rapidas.
        /// </summary>
        internal static string lblMenuCRapidas {
            get {
                return ResourceManager.GetString("lblMenuCRapidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargar.
        /// </summary>
        internal static string lblMenuDescargar {
            get {
                return ResourceManager.GetString("lblMenuDescargar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explorar.
        /// </summary>
        internal static string lblMenuExplorar {
            get {
                return ResourceManager.GetString("lblMenuExplorar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitar.
        /// </summary>
        internal static string lblMenuSolicitar {
            get {
                return ResourceManager.GetString("lblMenuSolicitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione el archivo que quiera compartir.
        /// </summary>
        internal static string lblVistaCompartirSeleccionar {
            get {
                return ResourceManager.GetString("lblVistaCompartirSeleccionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay archivos compartidos.
        /// </summary>
        internal static string lblVistaCompartirVerArchivos {
            get {
                return ResourceManager.GetString("lblVistaCompartirVerArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  bitNoders vivos.
        /// </summary>
        internal static string lblVistaConfiguracionBitNoders {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionBitNoders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efecto transision de botones.
        /// </summary>
        internal static string lblVistaConfiguracionEfectoBotones {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionEfectoBotones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efecto transparencia de sistema.
        /// </summary>
        internal static string lblVistaConfiguracionEfectoFade {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionEfectoFade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Español.
        /// </summary>
        internal static string lblVistaConfiguracionEspañol {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionEspañol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a General.
        /// </summary>
        internal static string lblVistaConfiguracionGeneral {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        internal static string lblVistaConfiguracionIdioma {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingles.
        /// </summary>
        internal static string lblVistaConfiguracionIngles {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionIngles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar con windows.
        /// </summary>
        internal static string lblVistaConfiguracionIniciarConWindows {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionIniciarConWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interfaz.
        /// </summary>
        internal static string lblVistaConfiguracionInterfaz {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionInterfaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a IP de coneccion.
        /// </summary>
        internal static string lblVistaConfiguracionIP {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limite bajada.
        /// </summary>
        internal static string lblVistaConfiguracionLimiteBajada {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionLimiteBajada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descargas simultaneas.
        /// </summary>
        internal static string lblVistaConfiguracionLimiteDescargas {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionLimiteDescargas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limite subida.
        /// </summary>
        internal static string lblVistaConfiguracionLimiteSubida {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionLimiteSubida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimizar a bandeja.
        /// </summary>
        internal static string lblVistaConfiguracionMinimizarBanjeda {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionMinimizarBanjeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efecto deslizante de menu.
        /// </summary>
        internal static string lblVistaConfiguracionMovimientoMenu {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionMovimientoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        internal static string lblVistaConfiguracionNombre {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ruta de descarga.
        /// </summary>
        internal static string lblVistaConfiguracionRutaDescarga {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionRutaDescarga", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sincronizacion continua.
        /// </summary>
        internal static string lblVistaConfiguracionSyncAuto {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionSyncAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema.
        /// </summary>
        internal static string lblVistaConfiguracionTema {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Claro.
        /// </summary>
        internal static string lblVistaConfiguracionTemaClaro {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionTemaClaro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Oscuro.
        /// </summary>
        internal static string lblVistaConfiguracionTemaOscuro {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionTemaOscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferencias.
        /// </summary>
        internal static string lblVistaConfiguracionTranseferecias {
            get {
                return ResourceManager.GetString("lblVistaConfiguracionTranseferecias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se encontraron archivos.
        /// </summary>
        internal static string lblVistaExplorarPerdon {
            get {
                return ResourceManager.GetString("lblVistaExplorarPerdon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay archivos disponibles para descargar.
        /// </summary>
        internal static string lblVistaExplorarSyncOFF {
            get {
                return ResourceManager.GetString("lblVistaExplorarSyncOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Busca un archivo para explorar.
        /// </summary>
        internal static string lblVistaExplorarSyncON {
            get {
                return ResourceManager.GetString("lblVistaExplorarSyncON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Solicita el archivo que necesites!.
        /// </summary>
        internal static string lblVistaSolicitarInformacion {
            get {
                return ResourceManager.GetString("lblVistaSolicitarInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay nuevas solicitudes.
        /// </summary>
        internal static string lblVistaSolicitarNuevasSolicitudes {
            get {
                return ResourceManager.GetString("lblVistaSolicitarNuevasSolicitudes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a bitNode ya se encuentra en ejecucion..
        /// </summary>
        internal static string mensajebitNodeActivo {
            get {
                return ResourceManager.GetString("mensajebitNodeActivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email copiado al portapapeles..
        /// </summary>
        internal static string mensajeEmail {
            get {
                return ResourceManager.GetString("mensajeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error, vuelva a interntarlo..
        /// </summary>
        internal static string mensajeErrorCompartirArchivo {
            get {
                return ResourceManager.GetString("mensajeErrorCompartirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La IP introducida no es valida..
        /// </summary>
        internal static string mensajeErrorIP {
            get {
                return ResourceManager.GetString("mensajeErrorIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo fue compartido exitosamente..
        /// </summary>
        internal static string mensajeExitoCompartirArchivo {
            get {
                return ResourceManager.GetString("mensajeExitoCompartirArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al configurar, intente ejecutar como administrador..
        /// </summary>
        internal static string MensajeIniciarConWindows {
            get {
                return ResourceManager.GetString("MensajeIniciarConWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi IP: .
        /// </summary>
        internal static string miIP {
            get {
                return ResourceManager.GetString("miIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La solicitud fue enviada, solo queda esperar..
        /// </summary>
        internal static string msgSolicitarArchivo {
            get {
                return ResourceManager.GetString("msgSolicitarArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo solicitado no existe..
        /// </summary>
        internal static string msjASNULL {
            get {
                return ResourceManager.GetString("msjASNULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese una breve descripcion.
        /// </summary>
        internal static string msjDescripcion {
            get {
                return ResourceManager.GetString("msjDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Direccion IP copiada a portapapeles..
        /// </summary>
        internal static string msjIPPortapapeles {
            get {
                return ResourceManager.GetString("msjIPPortapapeles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debera buscar por el nombre del archivo para explorar..
        /// </summary>
        internal static string msjSyncOFF {
            get {
                return ResourceManager.GetString("msjSyncOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta funcion consume mas ancho de banda, pero en &apos;Explorar&apos; vera todos los archivos compartidos..
        /// </summary>
        internal static string msjSyncON {
            get {
                return ResourceManager.GetString("msjSyncON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Por favor ingrese minimo 5 tags separados por un espacio.
        /// </summary>
        internal static string msjTagNull {
            get {
                return ResourceManager.GetString("msjTagNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargando archivos.
        /// </summary>
        internal static string splashCargandoArchivos {
            get {
                return ResourceManager.GetString("splashCargandoArchivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Este proyecto fue realizado por alumnos de 3er año de la Universidad de la Punta (ULP) para la materia optativa programación concurrente como objetivo de cursada.
        /// </summary>
        internal static string tbVistaAboutDescripcion {
            get {
                return ResourceManager.GetString("tbVistaAboutDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Breve descripcion del archivo..
        /// </summary>
        internal static string tbVistaCompartirDescripcionArchivo {
            get {
                return ResourceManager.GetString("tbVistaCompartirDescripcionArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese minimo 5 tags separados por un espacio.
        /// </summary>
        internal static string tbVistaCompartirTags {
            get {
                return ResourceManager.GetString("tbVistaCompartirTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre del archivo..
        /// </summary>
        internal static string tbVistaExplorarBuscar {
            get {
                return ResourceManager.GetString("tbVistaExplorarBuscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reconectar.
        /// </summary>
        internal static string ttReconectar {
            get {
                return ResourceManager.GetString("ttReconectar", resourceCulture);
            }
        }
    }
}
